#!/usr/bin/env bun
/**
 * Rebuild data/intent-index.json + data/intents.json from data/intents-raw.json
 * WITHOUT re-calling OpenAI. Use this when you change indexing logic but the
 * paraphrases are fine.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import MiniSearch from "minisearch";
import { features } from "web-features";

const REPO = new URL("..", import.meta.url).pathname;
const DATA_DIR = join(REPO, "data");
const RAW_PATH = join(DATA_DIR, "intents-raw.json");
const INDEX_PATH = join(DATA_DIR, "intent-index.json");
const INTENTS_PATH = join(DATA_DIR, "intents.json");

interface RawFeature {
	id: string;
	paraphrases: string[];
	replaces: string[];
	error?: string;
}

// Replaces axis hygiene: the LLM was too generous claiming features replace
// popular libs (162 features said "floating-ui" — most are wrong). Curated
// whitelist: only features in these allowlists can legitimately claim each lib.
const REPLACES_WHITELIST: Record<string, Set<string>> = {
	"floating-ui": new Set([
		"anchor-positioning",
		"popover",
		"absolute-positioning",
		"sticky-positioning",
	]),
	"popper.js": new Set([
		"anchor-positioning",
		"popover",
		"absolute-positioning",
	]),
	"framer-motion": new Set([
		"view-transitions",
		"cross-document-view-transitions",
		"active-view-transition",
		"view-transition-class",
		"transitions",
		"transition-behavior",
		"animations",
		"animation-composition",
		"interpolate-size",
		"starting-style",
		"scroll-driven-animations",
		"scroll-timeline",
		"animation-timeline",
	]),
	"react-spring": new Set([
		"transitions",
		"animations",
		"interpolate-size",
		"starting-style",
		"animation-composition",
	]),
	"react-transition-group": new Set([
		"view-transitions",
		"cross-document-view-transitions",
		"transitions",
		"starting-style",
		"animations",
	]),
	"gsap": new Set([
		"animations",
		"scroll-driven-animations",
		"scroll-timeline",
		"animation-timeline",
		"view-transitions",
	]),
	"anime.js": new Set([
		"animations",
		"scroll-driven-animations",
		"transitions",
	]),
	"velocity.js": new Set(["animations", "transitions"]),
	"scrollmagic": new Set([
		"scroll-driven-animations",
		"scroll-timeline",
		"animation-timeline",
	]),
};

// Generic terms the LLM cited that don't help search at all
const REPLACES_BLOCKLIST = new Set([
	"manual js positioning",
	"manual css adjustments",
	"jquery",
	"bootstrap",
	"canvas",
	"javascript",
	"js",
	"custom css",
	"inline styles",
]);

function cleanReplaces(featureId: string, replaces: string[]): string[] {
	return replaces.filter((lib) => {
		if (REPLACES_BLOCKLIST.has(lib)) return false;
		const allowlist = REPLACES_WHITELIST[lib];
		// If we have a curated allowlist for this lib, enforce it
		if (allowlist) return allowlist.has(featureId);
		// Otherwise let it pass (long tail of niche libs trusted to be specific)
		return true;
	});
}

/**
 * If a paraphrase mentions a JS lib by name (e.g. "without floating-ui"),
 * but this feature is not in the whitelist for that lib, the paraphrase is a
 * lie generated by the LLM. Drop those paraphrases — they are noise.
 *
 * Paraphrases that don't mention any JS lib pass through unchanged.
 */
function cleanParaphrases(featureId: string, paraphrases: string[]): string[] {
	const libPatterns: Array<[string, RegExp]> = Object.keys(REPLACES_WHITELIST)
		.map((lib) => {
			// Match the lib name as a whole token, allow common spelling variants
			const escaped = lib.replace(/[.+]/g, (c) => `\\${c}`).replace(/-/g, "[- ]");
			return [lib, new RegExp(`\\b${escaped}\\b`, "i")] as [string, RegExp];
		});

	return paraphrases.filter((p) => {
		for (const [lib, re] of libPatterns) {
			if (re.test(p)) {
				// Paraphrase mentions a lib — only keep if feature is in the
				// whitelist for that lib.
				const allowed = REPLACES_WHITELIST[lib]?.has(featureId);
				if (!allowed) return false;
			}
		}
		return true;
	});
}

async function main() {
	const raw = JSON.parse(await readFile(RAW_PATH, "utf-8")) as Record<
		string,
		RawFeature
	>;
	const entries = Object.values(raw).filter((r) => !r.error);

	// Stats: before vs after cleaning
	const beforeFreq = new Map<string, number>();
	const afterFreq = new Map<string, number>();
	for (const r of entries) {
		for (const lib of r.replaces) {
			beforeFreq.set(lib, (beforeFreq.get(lib) ?? 0) + 1);
		}
		for (const lib of cleanReplaces(r.id, r.replaces)) {
			afterFreq.set(lib, (afterFreq.get(lib) ?? 0) + 1);
		}
	}
	console.log("replaces hygiene (before -> after curated):");
	for (const lib of Object.keys(REPLACES_WHITELIST)) {
		console.log(`  ${lib.padEnd(28)} ${beforeFreq.get(lib) ?? 0} -> ${afterFreq.get(lib) ?? 0}`);
	}

	// Build documents
	const docs: Array<{
		id: string;
		text: string;
		replaces: string;
		feature_id: string;
		kind: "paraphrase" | "replaces" | "name";
	}> = [];
	let nextId = 0;
	for (const r of entries) {
		const feature = features[r.id];
		if (!feature) continue;
		// 1. The feature name itself (high signal)
		const name = feature.name ?? r.id;
		docs.push({
			id: String(nextId++),
			text: name,
			replaces: "",
			feature_id: r.id,
			kind: "name",
		});
		// 2. Each paraphrase, after dropping lib-name lies
		const cleanedParaphrases = cleanParaphrases(r.id, r.paraphrases);
		for (const p of cleanedParaphrases) {
			docs.push({
				id: String(nextId++),
				text: p,
				replaces: "",
				feature_id: r.id,
				kind: "paraphrase",
			});
		}
		// 3. Replaces axis as its own doc per item, curated
		const cleanedLibs = cleanReplaces(r.id, r.replaces);
		for (const lib of cleanedLibs) {
			docs.push({
				id: String(nextId++),
				text: `without ${lib} alternative to ${lib} replace ${lib}`,
				replaces: lib,
				feature_id: r.id,
				kind: "replaces",
			});
		}
	}

	const index = new MiniSearch({
		fields: ["text", "replaces"],
		storeFields: ["feature_id", "text", "kind", "replaces"],
		searchOptions: {
			boost: { text: 2, replaces: 0.5 },
			fuzzy: 0.2,
			prefix: true,
		},
	});
	index.addAll(docs);
	await writeFile(INDEX_PATH, JSON.stringify(index.toJSON()));
	console.log(`saved ${INDEX_PATH} (${docs.length} docs indexed)`);

	// Lookup file with cleaned replaces
	const lookup: Record<
		string,
		{
			name: string;
			baseline: string;
			paraphrases: string[];
			replaces: string[];
		}
	> = {};
	for (const r of entries) {
		const feature = features[r.id];
		if (!feature) continue;
		lookup[r.id] = {
			name: feature.name ?? r.id,
			baseline: String(feature.status.baseline),
			paraphrases: cleanParaphrases(r.id, r.paraphrases),
			replaces: cleanReplaces(r.id, r.replaces),
		};
	}
	await writeFile(INTENTS_PATH, JSON.stringify(lookup));
	console.log(`saved ${INTENTS_PATH} (${Object.keys(lookup).length} feature lookups)`);

	console.log(`\ndone. ${entries.length} features, ${docs.length} indexed docs.`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
